### ISSUE TITLE
コメント内に [ ] が用いられていると、それ以降のエントリーが候補に表示されない

### ISSUE THREAD

**Issue by tattsan** [naokiri/cskk#244]
**簡潔な説明**
コメント内に [ ] が用いられていると、それ以降のエントリーが候補に表示されません。

**再現手順**
1. コメント内に [ ] を含むエントリーを持つ辞書を用いる。たとえば SKK-JISYO.L のとある版では「よし」は次のよう。
   ```
   よし /由/葦/葭/因/余資/余矢;[数学]versed cosine/好/良/美/吉/純/義/喜/善/佳/圭/慶/祥/芳/嘉/克/宜/淑/禎/禧/譱/縦/
   ```
2. スペースを叩いて可能な候補を次々に表示してゆく。
3. 上の「よし」を例にとると、「余矢」は表示されず途中で辞書登録モードになってしまう。

**期待した動作**
辞書に登録された候補は全て表示する。

**動作環境**
 - cskkのバージョン v3.1.0

**その他**
- 辞書のエンコーディングは UTF-8 にしています。

**Comment by tattsan** [comment]
その後調べてみると、表示されない原因は「候補の多さ」ではなく「コメント内に [ ] が用いられている」こと
だと判明しました。Issue のタイトルやトップ記事を書き直しておきます。

**Comment by naokiri** [comment]
[]が関わっているとなると厳密な送り仮名の優先マッチのためのパースがコメントで働いてしまっているバグのようですね。詳しく調べてみます。

**Comment by tattsan** [comment]
さっそくのPR、ありがとうございます。不具合の解消を確認しました。

**Comment by naokiri** [comment]
修正したものをマージしたので、v3.1.1として今日デプロイします。
