### ISSUE TITLE
まる1 /①/❶/⓵/ と辞書に登録されたエントリーが変換されない

### ISSUE THREAD

**Issue by tattsan** [naokiri/cskk#252]
**バグの簡潔な説明**
`まる1 /①/❶/⓵/` と辞書に登録されたエントリーが変換されません。

**再現手順**
1. 辞書のエンコードをUTF-8 にする。
2. `まる1 /①/❶/⓵/` を辞書に登録する。
3. 変換できない。

**期待した動作**
変換できる。

**動作環境**
 - cskkのバージョン: v3.1.1

**その他の情報**
- このエントリーは `SKK-JISYO.JIS3_4` にあったものを UTF-8 に変換したものです。
-  `ibus-skk`, `emacs-ddskk`, UTF-8 改造した `uim-skk` では変換できました。
- 数値変換の対象と見て失敗しているのかも知れませんね。

**Comment by naokiri** [comment]
たしかに再現できました。土日にもっと調べてみます。

**Comment by naokiri** [comment]
@tattsan https://github.com/naokiri/cskk/releases/tag/v3.1.2 修正して新しいバージョンでリリースしました。また問題があったら教えてください。

**Comment by tattsan** [comment]
さっそくアップデートしました。ありがとうございます！
